* Emacs Taskrunner
This is an elisp library which aims to provide a way to retrieve all of the
tasks/targets from various build systems and execute them in a compilation buffer.

The ultimate goal is to use this library to provide the data necessary for an
interactive interface through helm/ivy/ido which will let the user select tasks
and run them. Additionally, it will also provide a task caching mechanism so the
tasks do not have to be retrieved over and over again.

A larger goal to be looked at down the line would be to use async
processes/threads so emacs does not freeze while the processes are being
retrieved. For the time being, the main focus is to find a way to reliably parse
and return all tasks from a project directory and execute them.

* Project Status
Currently, this project can is stable and can be used for the following
systems/frontends listed below.
** Supported Systems
*** Currently supported
**** Build/Task Systems
- [X] yarn/npm
- [X] Gulp
- [X] Grunt
- [X] Gradle
- [X] Jake
- [X] Apache ant
- [X] mix
- [X] leinengen
- [X] rake
- [X] cargo(Rust)
- [X] go(Golang)
- [X] Cask
- [X] Make
- [X] CMake
- [X] stack
- [X] cabal
**** User interfaces
- [X] ivy
- [X] helm
- [ ] ido
*** Planning to add support for
- [ ] Apache maven
- [ ] Meson/Ninja
- [ ] sbt
- [ ] Buck(?)
- [ ] Bazel(?)
- [ ] msbuild(?)
